language: 'ru'
# Текущий язык плагина (что бы язык изменился нужно перезагрузить сервер)
currentLan: 'ru'
# Не трогайте эту настройку

currencyList:
  - 'Diamond'
  - 'Gold'
# список валют вашего сервера
materialDiamond: 'DIAMOND'
# материал валюти под названием Diamonds (что бы выбрать материал для вашей валюты нужно писать по примеру: materialНазваниеВалюты)
materialGold: 'GOLD_INGOT'
# материал валюты под названием Gold (что бы выбрать материал для вашей валюты нужно писать по примеру: materialНазваниеВалюты)
exchangeRateDiamondToGold: 30
# курс валют, в данном примере 1 Diamonds = 30 GOLD, нужно, что бы подобное было для каждой валюты (пример создание для вашей валюты exchangeRateБольшеВалютаToМеньшаяВалюта)

ignoreBalansATDeleteCard: false
# игнорировать ли баланс банкомата при удалении карты (true - если на балансе банкомата недостаточно денег то остаток что на карте все равно будет выдан игроку,
# false - если в банкомате недостаточно денег то остаток игрок не будет получать с карты и карта не будет удалиться пока в банкомате не будет нужной суммы)

dataPlayerCard: 'UUID'
# в каком формате будут читаться данные об игроке (UUID - в формате ключа, NAME - в формате имени) рекомендуем UUID

maxCardCreate: 36
# максимум карт всех валют (не ставить больше 36)
maxCardCreateDiamond: 10
# максимум карт определенной валюты (пример создание maxCardCreateНазваниеВалюты)

maxCardCreateKotarych: 6
# максимум карт всех валют для определенного игрока (пример создание maxCardCreateНикнейИгрока)
maxCardCreateDiamondKotarych: 3
# максимум карт определенной валюты для определенного игрока (пример создание maxCardCreateВалютаНикнейм)