language: 'ua'
# Поточна мова плагина (щоб мова змінилась треба перезагрузити сервер)
currentLan: 'ua'
# Не чіпайте цю настройку

currencyList:
  - 'Diamond'
  - 'Gold'
# перелік валют
materialDiamond: 'DIAMOND'
# матеріал валюти під назвою Diamonds (щоб вибрати матеріал для вашої валюти треба вводити по прикладу: materialНазваВалюти)
materialGold: 'GOLD_INGOT'
# матеріал валюти під назвою Gold (щоб вибрати матеріал для вашої валюти треба вводити по прикладу: materialНазваВалюти)
exchangeRateDiamondToGold: 30
# курс валюти в даному прикладу 1 Diamonds = 30 GOLD, треба, щоб це було для кожної валюти (приклад створення для вашої валюти exchangeRateБільшаВалютаToМеншаВалюта)

ignoreBalansATDeleteCard: false
# чи ігнорувати баланс банкомата при видаленні картки (true - якщо при видаленні картки на ній є гроші й в банкоматі недостатньо грошей картка буде видалятися и залишок баланса картки буде видану гравцю,
# false - якщо при видаленні картки на ній є гроші й в банкоматі недостатньо грошей картка не буде видалятися)

dataPlayerCard: 'UUID'
# в якому форматі будуть читатися дані о гравці (UUID - у форматі ключа, NAME - у форматі імені) рекомендується UUID

maxCardCreate: 36
# максимум карт всіх валют (не ставити понад 36)
maxCardCreateDiamond: 10
# максимум карт визначених валют (приклад створення maxCardCreateНазваВалюти)

maxCardCreateKotarych: 6
# максимум карт всіх валют для визначеного гравця (приклад створення maxCardCreateНікнеймГравця) (не ставити понад 36)
maxCardCreateDiamondKotarych: 3
# максимум карт для визначеного гравця визначеної валюти (приклад створення maxCardCreateВалютаНікнейм)